### ISSUE TITLE
[Feature] Add Labels  in Application Card ，support quick editing and query filter

### ISSUE THREAD

**Issue by ranger-huang** [kubevela/velaux#240]
<img width="1517" alt="wecom-temp-d8b4d460f93f55a204b9f96cecb9a2c8" src="https://user-images.githubusercontent.com/32536203/144359445-28cba9fa-642f-463b-aaaf-5080f4f600d4.png">

# 功能：

1. 在应用卡片中展示 "key: value" 内容的 labels 小方块 ,  可根据的正则匹配或前缀匹配，需要显示的label key
2. 相同的 label key , 在所有应用中采用同一个配色，
3. 可以直接在应用卡片中，快速添加、编辑、删除 label
4. 可以通过点击应用卡片中的 label， 快速按label key=value 查询 应用列表

# 例子：

1. 显示：按需在应用卡片中，按"^ddd\.(.+)"正则 或  "ddd." 前缀，在卡片中显示 label小方块列表
```json
# application list
{
  "applications": [{
            "labels": {
                "project.module": "erp",
                "ddd.domain": "insurance",
                "ddd.subdomain": "account"
            },
            ...
   }, 
   ...]
...
}
```

2. 配色：如有以下 应用卡片
- "ddd.domain: insurance"  ， "ddd.subdomain: account"
- "ddd.domain: insurance"  ， "ddd.subdomain: docs"

小方块key ddd.domain 可能是红色，key ddd.subdomain 可能是橙色

3. 快捷编辑：应用卡片中的 label 栏上，
- 预留一个白底灰边的小方块占位符，用于快速 *添加* 新 label ，期间提供label key/value的快速提示和选择；如新label key与已有的 key 有重复，替换原有 label 的 value
- label 小方块最左侧显示 "x" 用于快速点击删除 label

4. 快捷查询：应用卡片中的 label 小方块，可以快速点击 value 部分，快速查询过滤应用，参考 [k8s labelSelector](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#label-selectors) 
    a.  选择多个不同的 label key 代表 `and` 查询，如 
        -  ` ddd.domain in (insurance) , ddd.subdomain in (account) ` 
    b.  选择同一个label key 的不同value ，代表 `or` 查询，如：
        - ` ddd.domain in (insurance, trade) `
        - ` ddd.domain in (insurance) , ddd.subdomain in (account, docs) ` 

---

一些扩展性的实现思路： 利用cue模版的扩展方式，如定制 x-definition 般来 实现 应用卡片UI  的定制化展示，甚至提供编辑、修改的metadata.labels/annotations 的校验功能

**Comment by barnettZQG** [comment]
@ranger-huang 从你的描述看，你是建议基于label模式实现对应用的分类？

**Comment by ranger-huang** [comment]
> @ranger-huang 从你的描述看，你是建议基于label模式实现对应用的分类？

是的， 因为整个项目的微服务数量多，组织成应用的数量也较多，通过 `应用划分` 和 `领域划分` 的两次划分组织application，可以降低应用管理复杂性。

我的实践方式如下：

假设有 blog、wiki、tms、crm、erp .... N款应用，以一个博客应用 crm 为例

### A. 第一层划分，是以应用为单位进行微服务的划分。
以Application为单位可以封装一个原子性的具有完整用户价值的应用，应用有复数多个component组成。
在遵循 [12factory 的后端服务](https://12factor.net/zh_cn/backing-services) 的规则情况下， crm app应该有component ：
1. 前端内容展示界面 crm-customer
2. 后端服务 crm-service
3. 管理端界面服务 crm-admin
4. 后台消费者任务 crm-worker
5. 中间件/持久化存储 crm-database / crm-cache / crm-mq 
6. 数据迁移任务 crm-datamigration 

以上中之一的component，都不能提供完整的用户价值；
而通过Application可以将所有组件包装成一个完整应用，提供完整且独立的业务价值。

### B. 第二层划分，是以 label 模式进行 领域建模(DDD)， 把N款划分成 m个领域/子域。

一般较大的平台，有20+个应用是比较正常的，
1. 20个应用 分4个大领域(ddd.domain) 平均每个领域就只有5个应用
2. 在1的基础上每个领域再划分2-4个子域，一个子域中的应用就有1-3个应用

### 最后
20款应用，每个Application中都有 8-10个component，总共就有160-200个component。
经过 `A. 应用划分` 和 `B.领域划分` 之后，一个子域的 Application数量及之内的Component数量 规模，可以被一个10-15人团队所掌控。一个团队的开发者或业务人员的用户视角中，只需要关心1-3个应用。

研发管理的复杂度就可以通过上面的方式降低了。
