### ISSUE TITLE
[Feature]  API and UI authentication based on RBAC, Use RoleTemplate

### ISSUE THREAD

**Issue by fzyleft** [kubevela/velaux#404]
API and UI authentication based on RBAC
**Basic concepts**
        Resource:  Data requiring permission control.      example:  Project、Application
        Action:  Performed on resources             example: Create、Delete
        Effect: Allow or Reject
        Condition: Effective conditions          example: Within a time period
        
        Role: Used to implement RBAC permission model
        RoleTemplate: Role abstraction
        PublicPolicy: Describe permissions on resources independently of any identity
        Privatepolicy: Belongs to a specific identity , Describe permissions on resources

**Model**
    
![12](https://user-images.githubusercontent.com/102162121/160061658-0d0ab658-0593-4d70-8ab9-f18054805361.png)

    Project RoleTemplate Private Policy
      example:  project-admin   
          {
              "Effect": "allow",
              "Action": ["ProjectView"],
              "Resource": “project/<projectName>”,
              “Condition”：{}
          }
    
        can also set application related permissions under the project
          {
              "Effect": "allow",
              "Action": ["ApplicationCreate","ApplicationRestart"],
              "Resource": “project/<projectName>/application/*”,
              “Condition”：{}
          }

    Application RoleTemplate Private Policy
      example:  application-admin   
          {
              "Effect": "allow",
              "Action": ["ApplicationCreate","ApplicationRestart"],
              "Resource": “project/<projectName>/application/<applicationName>”,
              “Condition”：{}
          }
        can also set related permissions of the project which the application belongs to
          {
              "Effect": "allow",
              "Action": ["ProjectView"],
              "Resource": “project/<projectName>”,
              “Condition”：{}
          }

    Instantiate the role of a specific resource based on the role template
         example:    
            Role：  LT31-project-admin
 	    Permission: project/LT31 ProjectView ;  project/LT31/application/*  ApplicationView
       
    Add or remove users to a role to control the action permission

**Authentication**
    Match  the union of the permissions of all roles  which the user belongs

**Comment by barnettZQG** [comment]
@fzyleft This is a good proposal, we already support the RBAC in 1.3, it is similar to your proposal.  Ref: oam-dev/kubevela#3493
