### ISSUE TITLE
验证用户填写的镜像

### ISSUE THREAD

**Issue by zzxwill** [kubevela/velaux#436]
当用户填写的镜像是私有镜像，并且镜像的 registry url 已经在配置里注册了，如果不合法：

- 镜像地址错误
- 镜像 tag 不存在

前端返回错误，给用户告警。

如果是 image registry 的 url/username/password 写错了，需要给出创建配置错误的提示，引导用户去创建新的 image registry 配置。

**Comment by barnettZQG** [comment]
用户填写的任何镜像名称，后端进行合法性校验，校验流程包括：

1. 直接验证，通过则代表其为公开镜像。
2. 匹配私服仓库授权配置，进行私服校验。
3. 通过上述校验确定镜像地址是否存在。不存在响应对应错误码，存在则响应 secret 名称，和下述镜像信息（选择性实现）：
    * 镜像元数据中的端口，volume目录，环境变量列表。

**Comment by zzxwill** [comment]
验证用户的私有镜像和 docker hub 上公开镜像。

其他公开的镜像，ghcr, gcr 逐步支持中。
