### ISSUE TITLE
辅助用户填写 imagePullSecrets

### ISSUE THREAD

**Issue by zzxwill** [kubevela/velaux#437]
如果[验证用户填写的镜像](https://github.com/oam-dev/velaux/issues/436)通过，用户在填写 imagePullSecrets 时，提供

下拉列表

供用户选择一个 secret，该 secret 来源于镜像验证后返回。

- 如果只有一个 secret，默认填上
- 如果有多个，提供列表，供用户选择。
- 如果没有，需要提供「文本框」，供用户填写。

**Comment by barnettZQG** [comment]
@zzxwill  
1. 验证镜像时返回的secret只需要一个，不应该多个。
2. secret 的选择项通过独立的接口获取，应包括项目下所有镜像仓库授权配置（可选实现）。

**Comment by zzxwill** [comment]
> @zzxwill
> 
> 1. 验证镜像时返回的secret只需要一个，不应该多个。
用户可能创建多个 registry url 一样的配置
