### ISSUE TITLE
Can not auto redirect to login page when token is expired.

### ISSUE THREAD

**Issue by wangcanfengxs** [kubevela/velaux#479]
When The token is expired, the page is always loading.
I think it should auto redirect to login page.

**Comment by wangbow** [comment]
Did you log in with SSO or Local, it is convenient to record a video so that developers can get more detailed information

**Comment by barnettZQG** [comment]
@wangcanfengxs Please upgrade the VelaUX addon to the 1.3.2 version.
```
vela addon enbale velaux --version=v1.3.2
```
