### ISSUE TITLE
UI not working after installation (blocker)

### ISSUE THREAD

**Issue by EikeHens** [kubevela/velaux#490]
Application page not shown after fresh installation. login works but then after the redirect to the /applications page is emtpy.

vela version: 1.3.2
velaux                          KubeVela        KubeVela User Experience (UX). An extensible, application-oriented delivery and management Dashboard.   [v1.3.2, v1.3.1, v1.3.0, ...]   enabled (v1.3.2)

**Comment by barnettZQG** [comment]
@EikeHens Maybe this is the same with #488

**Comment by barnettZQG** [comment]
This is already fixed in v1.3.3.
