### ISSUE TITLE
env is not synced while deploy the first-app

### ISSUE THREAD

**Issue by wonderflow** [kubevela/velaux#510]
**Describe the bug**

I have deployed the first app in the docs. https://kubevela.io/docs/quick-start

![image](https://user-images.githubusercontent.com/2173670/168563142-2cb9967c-ac5b-43e5-8f10-4ba1749da09f.png)

When I open the velaux dashboard, it shows  not deployed in `syc-default` environment whiile it's normal in syc-prod.

![image](https://user-images.githubusercontent.com/2173670/168563584-6d0df28b-2809-4420-a8e1-673c550cf91c.png)

My first app runs normally.

**To Reproduce**

Follow the instructions in  https://kubevela.io/docs/quick-start

**Expected behavior**

**Screenshots**

**KubeVela Version**

**Additional context**

**Comment by barnettZQG** [comment]
This issue can not reproduce, I will close it.
