### ISSUE TITLE
集成dex的登录页面频繁跳转

### ISSUE THREAD

**Issue by fengkang01** [kubevela/velaux#591]
**Describe the bug**

在通过dex集成sso之后访问登录页面会频繁的在login界面和dex界面进行跳转，相同的情况也会发生在用户登出之后
**To Reproduce**

**Expected behavior**

在访问到对应的url之后跳转到对应的dex页面
**Screenshots**

<img width="960" alt="e6a72b40b00f037f1d0b59196f952fc" src="https://user-images.githubusercontent.com/103910304/179952400-48e1638a-f6c7-4015-90bb-a0b479b10e79.png">
<img width="960" alt="1010deac4249eb423ac92197e864c8a" src="https://user-images.githubusercontent.com/103910304/179952426-951b8ea7-84bd-424a-819d-36e8ec137c1e.png">

**KubeVela Version**
CLI Version: v1.4.0
Core Version: 1.4.0
GitRevision: git-8f7a825
GolangVersion: go1.17.10

**Additional context**

**Comment by barnettZQG** [comment]
@fengkang01 你遇到该问题的主要原因是没有在 VelaUX 插件中启用 dex 路由。 请将 VelaUX 升级到 1.4.7 版本，同时在 VelaUX 插件配置中打开 dex 开关。

![image](https://user-images.githubusercontent.com/18493394/180601977-f2982f02-ce10-4219-8a8a-0d8020fc5ced.png)

**Comment by barnettZQG** [comment]
fixed by #601
