### ISSUE TITLE
[Bug] webpage crash when input by keyboard

### ISSUE THREAD

**Issue by StevenLeiZhang** [kubevela/velaux#651]
**Describe the bug**

webpage crash when input by keyboard
**To Reproduce**
1. Install velaux
2. click button "New Application"
3. click button "Next Step"
4. click textbox "Secret"
5. click keyboard to input
6. the webpage crash

https://user-images.githubusercontent.com/14890978/209745729-d5bbcb41-875c-4153-b4a5-867d918f66f2.mov

**Expected behavior**
1. webpage works well

**Screenshots**

**KubeVela Version**

**Additional context**

**Comment by barnettZQG** [comment]
@StevenLeiZhang I can't reproduce it. What's your version?

**Comment by StevenLeiZhang** [comment]
> @StevenLeiZhang I can't reproduce it. What's your version?


UI Version: v1.6.4-2f68a03

API Version: v1.6.4-git-1a6b724

I can not reproduce it now too.
