### ISSUE TITLE
[Feature] Custom annotation add for application edit page

### ISSUE THREAD

**Issue by previousdeveloper** [kubevela/velaux#665]
**Is your feature request related to a problem? Please describe.**
The application edit page offers editing application labels, in addition to the label is it possible to add a custom annotation area for the application?

**Describe the solution you'd like**
Custom annotation input area to add key-value pair.
<img width="799" alt="Screen Shot 2023-01-17 at 22 07 00" src="https://user-images.githubusercontent.com/6371971/212989492-58c60f9d-410b-43dc-958c-0b480bd1be4b.png">

**Comment by wonderflow** [comment]
good idea!

**Comment by yikuaibro** [comment]
@wonderflow Excuse me, is this done? Can I try it?

**Comment by barnettZQG** [comment]
@yikuaibro Yes. But you need to change the API to support this feature first.

**Comment by yikuaibro** [comment]
https://github.com/kubevela/kubevela/blob/9ecfa55056d952c9cb59291ee764fa99df19a311/pkg/apiserver/interfaces/api/application.go#L99-L108
I think this API is what you call.

**Comment by barnettZQG** [comment]
> https://github.com/kubevela/kubevela/blob/9ecfa55056d952c9cb59291ee764fa99df19a311/pkg/apiserver/interfaces/api/application.go#L99-L108 I think this API is what you call.

You are right.

**Comment by yikuaibro** [comment]
I'm a bit confused, ```Custom annotation input area to add key-value pair``` Does it mean adding a key-value pair block at the same level as Alias, Description, and Labels?
