### ISSUE TITLE
Is the application version information missing the processing logic of rollback status？

### ISSUE THREAD

**Issue by JayChou0716** [kubevela/velaux#695]
**Describe the bug**
The status column in the version list information is missing the processing of the rollback status, so the status display is empty

**To Reproduce**
1. Create an application
2. Add a suspend workflow
3. Click rollback after deployment

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/55052467/224660662-ccb90dbe-6485-4c0a-8722-70e56d53f846.png)

![image](https://user-images.githubusercontent.com/55052467/224660752-eb051419-61db-4dfc-9731-785824bf4f7a.png)

**KubeVela Version**
1.7.4

**Comment by barnettZQG** [comment]
Fixed by #696
