### ISSUE TITLE
[BUG] Can't load the category of the workflow step definition.

### ISSUE THREAD

**Issue by barnettZQG** [kubevela/velaux#702]
**Describe the bug**

Now, Frontend loads the step category from the label `definition.oam.dev/catalog`. But all step definitions define the category by the label `custom.definition.oam.dev/category`. Refer to this [PR change](https://github.com/kubevela/kubevela/commit/4a16b2f6fef159cbbc02e4cd627f8bb3ec37d4e8) It's not matched. 

![image](https://user-images.githubusercontent.com/18493394/225791625-0b6e4c27-da12-40f6-8e40-695dbab1a672.png)

So, we need to change the frontend code. The path is `packages/velaux-ui/src/components/WorkflowStudio/type-select.tsx`

**Comment by NeerajGartia21** [comment]
Can you please assign it to me?
