### ISSUE TITLE
Can't edit workflow on dashboard

### ISSUE THREAD

**Issue by 1ch0** [kubevela/velaux#782]
**Describe the bug**

**To Reproduce**

**Expected behavior**

1. Open  applications/busybox/envbinding/default/workflow/studio
2. Click on the plus sign
3. The browser window is white
**Screenshots**

![微信图片_20230419175516](https://user-images.githubusercontent.com/53722809/233039099-0c78d523-c9cc-4b14-aa97-b629a687dfc5.png)
![微信图片_20230419175522](https://user-images.githubusercontent.com/53722809/233039124-9c0e2c5c-75c3-40d9-a908-70d25823eff1.png)

**KubeVela Version**

**Additional context**

**Comment by barnettZQG** [comment]
@1ch0 Please upgrade VelaUX to 1.8.0 and retry to check this issue.

**Comment by 1ch0** [comment]
Problem solved after upgrading to 1.8
