### ISSUE TITLE
Unit of Memory

### ISSUE THREAD

**Issue by jiaxiaolei007** [kubevela/velaux#787]
**Describe the bug**
In the first step of application creation, is the unit of memory Mi or MB ?

**To Reproduce**
1. Creating a webservice application.
2. Fill in the memory value as 1024 (MB).
3. Click to create.
4. View the parameters passed to the backend

**Expected behavior**

The value on the UI interface is 1024MB, but the parameter value passed to the backend is 1024Mi。Therefore, I would like to confirm if the unit of memory in the underlying system is Mi?
**Screenshots**

![image](https://user-images.githubusercontent.com/55052467/233942691-3a324347-fa85-46c7-8c09-1bcab718ac3a.png)

![image](https://user-images.githubusercontent.com/55052467/233942215-0c46ce8c-c388-4cc6-9aee-3d30e1368285.png)

**KubeVela Version**

V1.6.5
**Additional context**

**Comment by barnettZQG** [comment]
@jiaxiaolei007 The right unit is MiB.

**Comment by jiaxiaolei007** [comment]
> @jiaxiaolei007 The right unit is MiB.
Therefore, both the parameters displayed on the interface and passed to the backend should be MiB, right？

**Comment by barnettZQG** [comment]
Fixed by #792
