### ISSUE TITLE
[BUG] Application Graph displays exception stack trace

### ISSUE THREAD

**Issue by unlenen** [kubevela/velaux#793]
Velaux Application Graph is failed when click to : applications/[APP-NAME]/envbinding/system/status  . An exception stack trace appears.

**To Reproduce**

1. Click an application
2. Click Enviroment
3. Click Status
4. Click Application Graph Tab

**Expected behavior**

Application graph of application

**Screenshots**
![image](https://user-images.githubusercontent.com/63339192/234548236-58fcfd78-c589-4e97-b48f-4323b640ef93.png)

**KubeVela Version**

1.8.0

**Additional context**

**Comment by barnettZQG** [comment]
@unlenen Are all application status pages failed?

**Comment by barnettZQG** [comment]
@unlenen Can you view and provide the application status API response data?

**Comment by unlenen** [comment]
> @unlenen Are all application status pages failed?

It fails for all applications .

No API call is  occoured when I click to application graph . I can share the api response when I click to status

`{
 "envName": "delivery-experience-dev",
 "status": {
  "conditions": [
   {
    "type": "Parsed",
    "status": "True",
    "lastTransitionTime": "2023-04-27T10:47:11Z",
    "reason": "Available"
   },
   {
    "type": "Revision",
    "status": "True",
    "lastTransitionTime": "2023-04-27T10:47:11Z",
    "reason": "Available"
   },
   {
    "type": "Policy",
    "status": "True",
    "lastTransitionTime": "2023-04-27T10:47:11Z",
    "reason": "Available"
   },
   {
    "type": "Render",
    "status": "True",
    "lastTransitionTime": "2023-04-27T10:47:11Z",
    "reason": "Available"
   },
   {
    "type": "Workflow",
    "status": "True",
    "lastTransitionTime": "2023-04-27T10:49:15Z",
    "reason": "Available"
   },
   {
    "type": "Ready",
    "status": "True",
    "lastTransitionTime": "2023-04-27T10:49:15Z",
    "reason": "ReconcileSuccess"
   }
  ],
  "observedGeneration": 2,
  "status": "running",
  "services": [
   {
    "name": "gokce-nginx",
    "namespace": "delivery-experience",
    "cluster": "p-platform-idp-kubevela-stage",
    "workloadDefinition": {
     "apiVersion": "apps/v1",
     "kind": "Deployment"
    },
    "healthy": true,
    "message": "Status:Healthy"
   }
  ],
  "workflow": {
   "appRevision": "workflow-delivery-experience-dev-20230427104909033",
   "mode": "StepByStep-DAG",
   "status": "succeeded",
   "suspend": false,
   "terminated": false,
   "finished": true,
   "contextBackend": {
    "kind": "ConfigMap",
    "namespace": "delivery-experience",
    "name": "workflow-gokce-nginx-context",
    "uid": "107da2be-da48-4942-9f95-2a60ac1d2490",
    "apiVersion": "v1"
   },
   "steps": [
    {
     "id": "lf8v2q3z8p",
     "name": "delivery-experience-dev",
     "type": "deploy",
     "phase": "succeeded",
     "firstExecuteTime": "2023-04-27T10:49:09Z",
     "lastExecuteTime": "2023-04-27T10:49:15Z"
    }
   ],
   "startTime": "2023-04-27T10:49:09Z",
   "endTime": "2023-04-27T10:49:15Z"
  },
  "latestRevision": {
   "name": "gokce-nginx-v2",
   "revision": 2,
   "revisionHash": "ecb7bc94f51cff0b"
  },
  "appliedResources": [
   {
    "cluster": "p-platform-idp-kubevela-stage",
    "creator": "workflow",
    "kind": "Rollout",
    "namespace": "delivery-experience",
    "name": "gokce-nginx",
    "apiVersion": "argoproj.io/v1alpha1"
   },
   {
    "cluster": "p-platform-idp-kubevela-stage",
    "creator": "workflow",
    "kind": "Service",
    "namespace": "delivery-experience",
    "name": "gokce-nginx",
    "apiVersion": "v1"
   },
   {
    "cluster": "p-platform-idp-kubevela-stage",
    "creator": "workflow",
    "kind": "Service",
    "namespace": "delivery-experience",
    "name": "gokce-nginx-preview",
    "apiVersion": "v1"
   },
   {
    "cluster": "p-platform-idp-kubevela-stage",
    "creator": "workflow",
    "kind": "VirtualService",
    "namespace": "delivery-experience",
    "name": "gokce-nginx",
    "apiVersion": "networking.istio.io/v1alpha3"
   },
   {
    "cluster": "p-platform-idp-kubevela-stage",
    "creator": "workflow",
    "kind": "ServiceAccount",
    "namespace": "delivery-experience",
    "name": "gokce-nginx",
    "apiVersion": "v1"
   }
  ]
 }
}`

**Comment by unlenen** [comment]
It is solved in 1.8.1 thanks
