### ISSUE TITLE
[BUG] Changing role of user to admin not works

### ISSUE THREAD

**Issue by unlenen** [kubevela/velaux#798]
**Describe the bug**
Changing role of user to admin not works

When we try to upgrade a user to admin role , nothings occurs . We also checked from mongodb , no update occurs. Update button does not work . When user logins to kubevela , can not see admin dashboard

**To Reproduce**
1. Click Admin Dashboard
2. Click Users
3. Select a user from list ( We have 1.7k user in list)
4. Click Edit
5. Select Admin from Platform Roles combobox
6. Click Update

**Expected behavior**

1. Update user record in mongodb (vela_user.userroles = "admin)
2. When user logins to kubevela shall access to admin dashboard

**Screenshots**
1. velaux page
![image](https://user-images.githubusercontent.com/63339192/234853378-7414b40e-9df7-478e-8b9e-5ba570038338.png)
2. mongodb records
![image](https://user-images.githubusercontent.com/63339192/234853677-31d3c25e-8bfd-4e7e-81da-5a620a89149b.png)
3. browser network console
![image](https://user-images.githubusercontent.com/63339192/234854239-4100a240-5c59-44f4-ab96-32bbd0ac4c8d.png)
4. browser script console
No script errors

**KubeVela Version**

v1.8.0

**Additional context**

**Comment by barnettZQG** [comment]
@unlenen The 1.8.1 version was released. You could upgrade later.

**Comment by unlenen** [comment]
It is solved in 1.8.1 thanks
