### ISSUE TITLE
[Feature]: can't see policy type when update policy 

### ISSUE THREAD

**Issue by mujinhuakai** [kubevela/velaux#799]
**Is your feature request related to a problem? Please describe.**

can't see policy type when update policy
![image](https://user-images.githubusercontent.com/10116106/235031102-a2b2c670-a0dd-401d-84a5-fdbb10cd3b25.png)

**Describe the solution you'd like**

**Describe alternatives you've considered**

display policy type when update
**Additional context**

**Comment by barnettZQG** [comment]
@mujinhuakai Policy type doesn't support updating.

**Comment by mujinhuakai** [comment]
> @mujinhuakai Policy type doesn't support updating.

But we want to know what's type the policy i'm editing
