### ISSUE TITLE
1.74 File Directory Changes After the upgrade to 1.8

### ISSUE THREAD

**Issue by zwtcici** [kubevela/velaux#831]
Has the file directory changed after the upgrade from 1.74 to 1.8? How do I start the front page and continue developing problems?
![image](https://github.com/kubevela/velaux/assets/53460851/21c5c03c-c3b8-4f29-93bb-24295b53d394)
![d3c3374ebf5d96a676ac9323adbf4e15](https://github.com/kubevela/velaux/assets/53460851/aaad1ddb-5799-4714-870a-ba819ad933e2)

**Comment by chivalryq** [comment]
API server has been migrated to velaux repo from KubeVela repo in 1.8. You can now start the server following instructions: https://github.com/kubevela/velaux/blob/main/docs/contributing/velaux.md

**Comment by chivalryq** [comment]
Closed and feel free to open if you have further question.

**Comment by zwtcici** [comment]
Now our service has been upgraded from 1.6 to 1.7, and we need to upgrade to 1.8, but the front end cannot be developed independently. How can we conduct the secondary development of the front end?

**Comment by chivalryq** [comment]
I'm not sure why you can not perform the secondary development now? You can still run code locally, the differences is developer have to start a server which provide both API and the frontend page (JS files).

**Comment by zwtcici** [comment]
Do you mean for velaux-ui in the packages file? But if you ask the front end to follow the documentation you provided, you need to install docker and start back-end services, but it is inconvenient to develop for the front end. Now don't you guys on the front end have a separate front end code?

**Comment by zwtcici** [comment]
Do you mean for velaux-ui in the packages file? But if you ask the front end to follow the documentation you provided, you need to install docker and start back-end services, but it is inconvenient to develop for the front end. Now don't you guys on the front end have a separate front end code?

**Comment by chivalryq** [comment]
> Do you mean for velaux-ui in the packages file?

Yes
> But if you ask the front end to follow the documentation you provided, you need to install 

docker and start back-end services, but it is inconvenient to develop for the front end.
The server code is merged with the front-end codebase for they can be developed together. If it causes any inconvenience I feel terrible. But still you can develop. cc @barnettZQG

**Comment by zwtcici** [comment]
If I install the antd dependency package in a project, which package.json file should I save it in?
Does this front-end project have antd dependency package requirements? Why is there an error after installation and the project build fails？

**Comment by chivalryq** [comment]
> If I install the antd dependency package in a project, which package.json file should I save it in?
We are using Fusion.design though. If you insist to install antd, velaux-ui should be the place.

If you have build problem you can paste the logs and screenshots.
