### ISSUE TITLE
[Feature] Add Info about all the supported actions for the custom triggers in the manual triggers page.

### ISSUE THREAD

**Issue by NeerajGartia21** [kubevela/velaux#834]
**Is your feature request related to a problem? Please describe.**

Since the approve, terminate and rollback actions are added for the custom triggers, we can add a sample request body for each of the actions in the manual triggers page.

<img width="820" alt="manual-trigger-8361fea9230d5f56d649dca15a33f1db" src="https://github.com/kubevela/velaux/assets/80708727/b8e7a0ca-d8ca-43a6-9cb3-4c090f1ff130">

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by chivalryq** [comment]
Looks good, here's a reference from Xata.
![image](https://github.com/kubevela/velaux/assets/47812250/b9a4a832-29e9-4f02-8636-7325aa218c96)
And in this case I think horizental tabs are better.

**Comment by NeerajGartia21** [comment]
Yeah, horizontal tabs will be best suitable.

Also I'm not able to add labels to the issue. Is it restricted?
