### ISSUE TITLE
can't load values.yaml from gitlab

### ISSUE THREAD

**Issue by cyxinda** [kubevela/velaux#847]
**Describe the bug**
I create application on velaux page.the values.yaml can't be loaded on the page.
![1111](https://github.com/kubevela/velaux/assets/7237898/40c30c07-7a74-4164-afcf-69bfdf33a98e)
the request of get values.yaml is : 
  ```json
  {
    "GET": {
      "scheme": "https",
      "host": "***.xxxx.com",
      "filename": "/api/v1/repository/chart/values",
      "query": {
        "repoUrl": "https://xxxxxxx.knowdee.com/api/v4/projects/4/packages/helm/stable",
        "repoType": "helm",
        "secretName": "tests-charts",
        "chart": "my-chart",
        "version": "0.1.0",
        "project": "default"
      },
      "remote": {
        "地址": "xxxxxx"
      }
    }
  }
  ```
the response is :
```json
    {
     "BusinessCode": 13003,
     "Message": "cannot get the values info of the chart"
    }
```
the url of the helm chart is https://github.com/cyxinda/my-chart/ ,you can see the content of the  helm chart.
you can push the helm charts above to gitlab with the command as follow:
```bash
root@ubuntu:#  helm repo add     --username root     --password glpat-xxxxxxx-vgSJju    charts  https://xxxx.knowdee.com/api/v4/projects/4/packages/helm/stable
"charts" has been added to your repositories
root@ubuntu:# ls
my-chart  my-chart-0.1.0.tgz
root@ubuntu:# helm cm-push my-chart charts
Pushing my-chart-0.1.0.tgz to charts...
Done.
root@ubuntu:# helm repo update charts
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "charts" chart repository
Update Complete. ⎈Happy Helming!⎈
root@ubuntu:# helm search repo charts
NAME            CHART VERSION   APP VERSION     DESCRIPTION                
charts/my-chart 0.1.0           1.16.0          A Helm chart for Kubernetes

```

my helm chart repository is gitlab(the version is 16.0).
![2222](https://github.com/kubevela/velaux/assets/7237898/e0c695e5-979b-47cd-95be-6335bb5f44a3)

**Expected behavior**
The content of values.yaml can be loaded normally on the velaux page.

**KubeVela Version**
1.8.2

**Comment by chivalryq** [comment]
Can you show the log of velaux apiserver?

**Comment by cyxinda** [comment]
> Can you show the log of velaux apiserver?

I don't know which pod is velaux apiserver.
```bash
[root@xy-5-server19 ~]# kubectl -n vela-system get pods
NAME                                                 READY   STATUS             RESTARTS   AGE
kubevela-cluster-gateway-54957bf4db-kkzjw            1/1     Running            0          9d
kubevela-vela-core-66c6d7ff76-fwb6k                  1/1     Running            0          9d
velaux-server-5b88988bf9-pc8r2                       1/1     Running            0          3m47s
```
I guess It is  the logs you focus:
![1111](https://github.com/kubevela/velaux/assets/7237898/fb2d6fdf-580a-46ba-b767-58d16076fcc2)
I don't think it has useful information.

**Comment by chivalryq** [comment]
I'm sure there are some log related with this response. Code around is like:
```go
	if err != nil {
		klog.Errorf("cannot fetch chart values repo: %s, chart: %s, version: %s, error: %s", utils.Sanitize(repoURL), utils.Sanitize(chartName), utils.Sanitize(version), err.Error())
		return nil, bcode.ErrGetChartValues
	}
```

I'm not sure but did you check the logs right after you try to load the values.yaml?

**Comment by cyxinda** [comment]
this is not only gitlab,   the harbor under version of 2.8 with chartmuseum plugin cannot   load   values.yaml,too.
![1111](https://github.com/kubevela/velaux/assets/7237898/9d91fb2c-6a5a-4bfd-bfd1-d90913e5ed66)
you can check this like this helm chart:
 `helm repo add  tests   https://registry.knowdee.com/chartrepo/tests`

**Comment by cyxinda** [comment]
the same problem happen when I use the example helm chart of kube-vela official document.
It refre to as follow:
![2222](https://github.com/kubevela/velaux/assets/7237898/5ea0c04c-2c0c-494b-abe2-a866e810883c)
![3333](https://github.com/kubevela/velaux/assets/7237898/26561d92-32b0-49ad-aa0d-6733e5ed9bca)

**Comment by cyxinda** [comment]
this issue is resoved in the version of 1.9.2 .
