### ISSUE TITLE
velaux 1.9.1 claudshell can not open

### ISSUE THREAD

**Issue by lxkaka** [kubevela/velaux#855]
**Describe the bug**
claudshell can not open and show error below 
![image](https://github.com/kubevela/kubevela/assets/10549664/814873d2-5a13-4cfa-a376-56184cd74e2f)

**KubeVela Version**
v1.9.3
velaux version v1.9.1

**Comment by wonderflow** [comment]
This is a velaux bug, so I transferred to velaux from kubevela.
