### ISSUE TITLE
Velaux encounters a "js-cache" error, which prevents the browser from accessing the Velaux backend.

### ISSUE THREAD

**Issue by imzhangsiwei** [kubevela/velaux#863]
**Describe the bug**

After running for a period of time, the Velaux backend cannot be accessed in the browser. Upon checking the Velaux logs, the following error is found:

```
E0725 02:57:38.652464       1 js-cache.go:75] failed to write the cache content, err: http: request method or response status code does not allow body

```

**To Reproduce**

**Expected behavior**

**Screenshots**

**KubeVela Version**
vela core 1.8.0
velaux 1.8.0

**Additional context**

**Comment by basuotian** [comment]
Fixed by https://github.com/kubevela/velaux/pull/814
